### ISSUE TITLE
[BUG]Repeat the send

### ISSUE THREAD

**Issue by 3JoB** [qini7-sese/eh2telegraph#2]
When the message in the channel is updated, the bot resends the pull message

[Example Video](https://bafybeieurwbtioa2li4rjx2nn2k3ompovtndx4qkqfh33q5lhrvtiajj6u.ipfs.dweb.link/Record_2022-06-20-23-13-42.mp4)

**Comment by ihciah** [comment]
It seems can be solved by filter out update message. Do you have interest to fix it?
