### ISSUE TITLE
[Feature request] Sync nhentai.xxx galleries to Telegraph

### ISSUE THREAD

**Issue by Matcha-sama** [qini7-sese/eh2telegraph#3]
众所周知， nhentai.net 开启了 Cloudflare 的 DDoS 防护，导致 eh2telegraph 无法将画廊同步到 telegraph 
错误代码 `Sync to telegraph failed: HTTP status server error (503 Service Unavailable) for url (https://nhentai.net/g/******)` 
然而， nhentai.net 有一个附属站 nhentai.xxx ，可能属于nh官方，它没有cf的5秒盾
eh2telegraph 并没有针对 nhentai.xxx 的 collector （发送链接回复 `Unrecognized message.` ）
鉴于我不会 rust ，所以这是一个 feature request😢

**Comment by ihciah** [comment]
不好意思一直没看到这个 issue。
改动已提交，自动构建完成后将更新公共 Bot。
谢谢反馈！

**Comment by ihciah** [comment]
Close as already finished.
